mysqlConnection:
  host: localhost
  port: 3306
  user: ""
  password: 
  database: CLONEID
  schemaScript: CLONEID_schema.sql

cellSegmentation:
  backend: local
  input: ~/CellSegmentations/
  output: ~/CellSegmentations/output/
  tmp: ~/Downloads/tmp/
  bucket:
  region:
  endpoint:
  inputPrefix: inputs
  outputPrefix: outputs
